// eslint-config-next 16 ships native flat configs. The FlatCompat bridge that
// older Next projects use throws "Converting circular structure to JSON"
// against this version — import the flat configs directly instead.
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypeScript from 'eslint-config-next/typescript'

/**
 * Tailwind's numbered colour scales. Using one in a component hardcodes the
 * palette and breaks the single-file rebrand guarantee.
 */
const TAILWIND_COLOR_FAMILIES = [
  'slate',
  'gray',
  'zinc',
  'neutral',
  'stone',
  'red',
  'orange',
  'amber',
  'yellow',
  'lime',
  'green',
  'emerald',
  'teal',
  'cyan',
  'sky',
  'blue',
  'indigo',
  'violet',
  'purple',
  'fuchsia',
  'pink',
  'rose',
].join('|')

const COLOR_UTILITY_PREFIXES = ['bg', 'text', 'border', 'ring', 'fill', 'stroke', 'from', 'via', 'to'].join('|')

const numberedColorPattern = `(?:${COLOR_UTILITY_PREFIXES})-(?:${TAILWIND_COLOR_FAMILIES})-[0-9]{2,3}`
const hexColorPattern = '#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})\\b'

const THEME_TOKEN_MESSAGE =
  'Hardcoded colour. The palette is not signed off — use a semantic token instead ' +
  '(bg-primary, text-muted, border-border-default, text-price). Colour values belong ' +
  'only in src/styles/theme.css. See src/styles/themes/README.md.'

const eslintConfig = [
  ...nextCoreWebVitals,
  ...nextTypeScript,
  {
    rules: {
      '@typescript-eslint/ban-ts-comment': 'error',
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-empty-object-type': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          vars: 'all',
          args: 'after-used',
          ignoreRestSiblings: false,
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^(_|ignore)',
        },
      ],
      // Structured logging goes through Payload's logger; stray console calls
      // become noise in the Cloudflare log stream.
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'prefer-const': 'error',
      'no-var': 'error',
    },
  },
  {
    // Enforce the theming contract where components actually live.
    files: ['src/components/**/*.{ts,tsx}', 'src/app/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: `Literal[value=/${numberedColorPattern}/]`,
          message: THEME_TOKEN_MESSAGE,
        },
        {
          selector: `TemplateElement[value.raw=/${numberedColorPattern}/]`,
          message: THEME_TOKEN_MESSAGE,
        },
        {
          selector: `Literal[value=/${hexColorPattern}/]`,
          message: THEME_TOKEN_MESSAGE,
        },
      ],
    },
  },
  {
    ignores: [
      '.next/',
      '.open-next/',
      '.wrangler/',
      'cloudflare-env.d.ts',
      // Generated by Payload — do not hand-edit, do not lint.
      'src/migrations/**',
      'src/payload-types.ts',
      'src/app/(payload)/admin/importMap.js',
    ],
  },
]

export default eslintConfig
