/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    categories: Category;
    brands: Brand;
    orders: Order;
    pages: Page;
    media: Media;
    users: User;
    banners: Banner;
    reviews: Review;
    customers: Customer;
    coupons: Coupon;
    'stock-alerts': StockAlert;
    'stock-movements': StockMovement;
    counters: Counter;
    'price-history': PriceHistory;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'stock-alerts': StockAlertsSelect<false> | StockAlertsSelect<true>;
    'stock-movements': StockMovementsSelect<false> | StockMovementsSelect<true>;
    counters: CountersSelect<false> | CountersSelect<true>;
    'price-history': PriceHistorySelect<false> | PriceHistorySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('bg' | 'en') | ('bg' | 'en')[];
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: 'bg' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * One or two lines, shown on product cards and in search results.
   */
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sku: string;
  /**
   * Single-unit price in EUR, e.g. 12.50
   */
  basePrice: number;
  /**
   * What you pay per unit. Never shown to customers — used for margin reporting only.
   */
  costPrice?: number | null;
  unit: 'piece' | 'kg' | 'l' | 'm' | 'box' | 'pack' | 'set';
  /**
   * Optional. Cheaper unit prices at higher quantities. Ranges must not overlap, and only the last tier may be left open-ended.
   */
  pricingTiers?:
    | {
        /**
         * From this quantity
         */
        minQuantity: number;
        /**
         * Up to (leave empty for "and above")
         */
        maxQuantity?: number | null;
        /**
         * EUR per unit
         */
        pricePerUnit: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Discounted unit price in EUR. Must be lower than the base price.
   */
  salePrice?: number | null;
  /**
   * Optional. Empty means the sale starts immediately.
   */
  saleStartsAt?: string | null;
  /**
   * Optional. Empty means the sale runs until removed.
   */
  saleEndsAt?: string | null;
  /**
   * Running balance maintained from the stock ledger. To receive goods or write off damage, add a Stock Movement — editing this directly is recorded as a correction.
   */
  stock: number;
  minOrderQuantity: number;
  /**
   * Show a "low stock" badge at or below this level.
   */
  lowStockThreshold?: number | null;
  /**
   * Shipping weight in grams. Used for courier rate calculation.
   */
  weightGrams?: number | null;
  category?: (number | null) | Category;
  /**
   * Optional. Products without a brand still list normally.
   */
  brand?: (number | null) | Brand;
  /**
   * Manually curated "frequently bought together" products. Overrides the automatic same-category suggestions when set.
   */
  crossSell?: (number | Product)[] | null;
  /**
   * The first image is used as the product thumbnail.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-generated from the title. Change with care — it is the public URL.
   */
  slug?: string | null;
  /**
   * Visible in the shop.
   */
  isActive?: boolean | null;
  /**
   * Show on the homepage.
   */
  isFeatured?: boolean | null;
  /**
   * Optional. Falls back to the title and short description.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  description?: string | null;
  image?: (number | null) | Media;
  /**
   * Optional parent category. Maximum three levels deep.
   */
  parent?: (number | null) | Category;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  isActive?: boolean | null;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers and search engines. Required.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  /**
   * The manufacturer name as it appears on the product.
   */
  name: string;
  description?: string | null;
  logo?: (number | null) | Media;
  /**
   * Optional link to the manufacturer's own site.
   */
  website?: string | null;
  slug?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'returned';
  customerName?: string | null;
  /**
   * Set when the order was placed by a signed-in customer. Guest orders have none.
   */
  customerAccount?: (number | null) | Customer;
  customer: {
    firstName: string;
    lastName: string;
    email: string;
    /**
     * Required — the courier needs it for Cash on Delivery.
     */
    phone: string;
    /**
     * Consent record — do not edit.
     */
    acceptedTerms: boolean;
    /**
     * Consent record — do not edit.
     */
    marketingConsent?: boolean | null;
  };
  shippingMethod: 'econt_office' | 'econt_address' | 'speedy_office' | 'speedy_address';
  /**
   * Courier office name or code.
   */
  officeCode?: string | null;
  shippingAddress?: {
    street?: string | null;
    city?: string | null;
    /**
     * Four digits (Bulgaria).
     */
    postalCode?: string | null;
    country?: string | null;
    /**
     * Delivery instructions.
     */
    notes?: string | null;
  };
  /**
   * Snapshot taken when the order was placed. Immutable.
   */
  items: {
    product?: (number | null) | Product;
    title: string;
    sku: string;
    quantity: number;
    unitPrice: number;
    totalPrice: number;
    /**
     * The 30-day reference price shown struck through at the time of sale. Kept so a discount dispute months later can be answered from the record.
     */
    referencePrice?: number | null;
    wasOnSale?: boolean | null;
    id?: string | null;
  }[];
  /**
   * EUR. Calculated server-side.
   */
  subtotal: number;
  /**
   * EUR. Calculated server-side.
   */
  shippingCost: number;
  /**
   * EUR. Coupon discount applied.
   */
  discount?: number | null;
  couponCode?: string | null;
  /**
   * EUR. Amount due on delivery.
   */
  total: number;
  courierService?: ('econt' | 'speedy') | null;
  /**
   * Required before an order can be marked as shipped.
   */
  trackingNumber?: string | null;
  /**
   * Internal only. Never shown to the customer.
   */
  adminNotes?: string | null;
  /**
   * Audit trail of status changes.
   */
  statusHistory?:
    | {
        status?: string | null;
        changedAt?: string | null;
        changedBy?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Set automatically when a cancellation or return puts this order's units back into stock. Prevents double-crediting if the status changes again.
   */
  stockRestored?: boolean | null;
  /**
   * Language the order was placed in — used for email language.
   */
  locale?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  firstName: string;
  lastName: string;
  phone?: string | null;
  /**
   * Pre-fills checkout. The customer can still change it per order.
   */
  defaultAddress?: {
    street?: string | null;
    city?: string | null;
    postalCode?: string | null;
    preferredShippingMethod?: ('econt_office' | 'econt_address' | 'speedy_office' | 'speedy_address') | null;
    officeCode?: string | null;
  };
  /**
   * Consent record — reflects what the customer chose.
   */
  marketingConsent?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  slug?: string | null;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Editors can manage products, categories, pages and orders — but not users or settings.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Promotional banners. Set dates to schedule; leave them empty to run immediately.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  title: string;
  subtitle?: string | null;
  /**
   * Wide image. Renders as a coloured panel when empty.
   */
  image?: (number | null) | Media;
  /**
   * Where the banner leads, e.g. /products?onSale=1
   */
  linkUrl?: string | null;
  /**
   * Button text. The whole banner is clickable if empty.
   */
  linkLabel?: string | null;
  placement: 'homepage_hero' | 'homepage_mid' | 'listing_top';
  startsAt?: string | null;
  endsAt?: string | null;
  sortOrder?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reviews are hidden until approved.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  product: number | Product;
  rating: number;
  authorName: string;
  title?: string | null;
  body?: string | null;
  /**
   * The verified purchase this review is attached to.
   */
  orderNumber?: string | null;
  isApproved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  /**
   * Case-insensitive. Stored and compared in upper case.
   */
  code: string;
  discountType: 'percent' | 'fixed' | 'free_shipping';
  /**
   * Percent (1-100) or EUR amount. Ignored for free shipping.
   */
  discountValue?: number | null;
  /**
   * Optional. Minimum order subtotal in EUR.
   */
  minimumSubtotal?: number | null;
  /**
   * Optional. Total redemptions allowed across all customers.
   */
  maxUses?: number | null;
  timesUsed?: number | null;
  startsAt?: string | null;
  endsAt?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-alerts".
 */
export interface StockAlert {
  id: number;
  product: number | Product;
  email: string;
  /**
   * Language to send the notification in.
   */
  locale?: string | null;
  /**
   * Set once the restock email has been sent. Empty means still waiting.
   */
  notifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every stock change and its reason. Add a movement to receive goods or write off damage — do not edit the stock field on a product directly.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements".
 */
export interface StockMovement {
  id: number;
  product: number | Product;
  /**
   * Positive to add stock, negative to remove. Zero is rejected.
   */
  delta: number;
  reason: 'sale' | 'cancellation' | 'return' | 'receiving' | 'damage' | 'stocktake' | 'correction';
  /**
   * Stock level immediately after this movement was applied.
   */
  balanceAfter?: number | null;
  /**
   * Order number, delivery note, or invoice reference.
   */
  reference?: string | null;
  /**
   * Who recorded it, or "system" for automatic movements.
   */
  recordedBy?: string | null;
  /**
   * Why. Especially worth filling in for damage and corrections.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Internal sequence counters, incremented atomically at checkout. Read-only by design.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counters".
 */
export interface Counter {
  id: number;
  /**
   * e.g. "orders:2026"
   */
  key: string;
  value: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Automatic record of price changes, used to compute the 30-day reference price required for advertised discounts. Read-only by law and by design.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-history".
 */
export interface PriceHistory {
  id: number;
  product: number | Product;
  /**
   * The effective selling price at this moment — sale price if one was active.
   */
  price: number;
  recordedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'stock-alerts';
        value: number | StockAlert;
      } | null)
    | ({
        relationTo: 'stock-movements';
        value: number | StockMovement;
      } | null)
    | ({
        relationTo: 'counters';
        value: number | Counter;
      } | null)
    | ({
        relationTo: 'price-history';
        value: number | PriceHistory;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  description?: T;
  sku?: T;
  basePrice?: T;
  costPrice?: T;
  unit?: T;
  pricingTiers?:
    | T
    | {
        minQuantity?: T;
        maxQuantity?: T;
        pricePerUnit?: T;
        id?: T;
      };
  salePrice?: T;
  saleStartsAt?: T;
  saleEndsAt?: T;
  stock?: T;
  minOrderQuantity?: T;
  lowStockThreshold?: T;
  weightGrams?: T;
  category?: T;
  brand?: T;
  crossSell?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  slug?: T;
  isActive?: T;
  isFeatured?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  parent?: T;
  sortOrder?: T;
  isActive?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  logo?: T;
  website?: T;
  slug?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  customerName?: T;
  customerAccount?: T;
  customer?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        email?: T;
        phone?: T;
        acceptedTerms?: T;
        marketingConsent?: T;
      };
  shippingMethod?: T;
  officeCode?: T;
  shippingAddress?:
    | T
    | {
        street?: T;
        city?: T;
        postalCode?: T;
        country?: T;
        notes?: T;
      };
  items?:
    | T
    | {
        product?: T;
        title?: T;
        sku?: T;
        quantity?: T;
        unitPrice?: T;
        totalPrice?: T;
        referencePrice?: T;
        wasOnSale?: T;
        id?: T;
      };
  subtotal?: T;
  shippingCost?: T;
  discount?: T;
  couponCode?: T;
  total?: T;
  courierService?: T;
  trackingNumber?: T;
  adminNotes?: T;
  statusHistory?:
    | T
    | {
        status?: T;
        changedAt?: T;
        changedBy?: T;
        id?: T;
      };
  stockRestored?: T;
  locale?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  slug?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  image?: T;
  linkUrl?: T;
  linkLabel?: T;
  placement?: T;
  startsAt?: T;
  endsAt?: T;
  sortOrder?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  rating?: T;
  authorName?: T;
  title?: T;
  body?: T;
  orderNumber?: T;
  isApproved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  defaultAddress?:
    | T
    | {
        street?: T;
        city?: T;
        postalCode?: T;
        preferredShippingMethod?: T;
        officeCode?: T;
      };
  marketingConsent?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  discountType?: T;
  discountValue?: T;
  minimumSubtotal?: T;
  maxUses?: T;
  timesUsed?: T;
  startsAt?: T;
  endsAt?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-alerts_select".
 */
export interface StockAlertsSelect<T extends boolean = true> {
  product?: T;
  email?: T;
  locale?: T;
  notifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements_select".
 */
export interface StockMovementsSelect<T extends boolean = true> {
  product?: T;
  delta?: T;
  reason?: T;
  balanceAfter?: T;
  reference?: T;
  recordedBy?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "counters_select".
 */
export interface CountersSelect<T extends boolean = true> {
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-history_select".
 */
export interface PriceHistorySelect<T extends boolean = true> {
  product?: T;
  price?: T;
  recordedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  siteName?: string | null;
  logo?: (number | null) | Media;
  /**
   * Main headline on the homepage.
   */
  heroHeading?: string | null;
  heroSubheading?: string | null;
  announcementBar?: {
    isActive?: boolean | null;
    text?: string | null;
    link?: string | null;
  };
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: string | null;
  socialLinks?:
    | {
        platform?: ('facebook' | 'instagram' | 'viber' | 'telegram') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  companyName?: string | null;
  /**
   * UIC / Bulstat
   */
  registrationNumber?: string | null;
  /**
   * If VAT registered
   */
  vatNumber?: string | null;
  registeredAddress?: string | null;
  tradeRegisterInfo?: string | null;
  /**
   * Flat rates in EUR, applied at checkout.
   */
  shippingRates?: {
    econtOffice?: number | null;
    econtAddress?: number | null;
    speedyOffice?: number | null;
    speedyAddress?: number | null;
    /**
     * Order subtotal above which shipping is free. Leave empty to disable.
     */
    freeShippingThreshold?: number | null;
  };
  /**
   * Shown on product pages and at checkout.
   */
  shippingInfo?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  footerText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  heroHeading?: T;
  heroSubheading?: T;
  announcementBar?:
    | T
    | {
        isActive?: T;
        text?: T;
        link?: T;
      };
  contactEmail?: T;
  contactPhone?: T;
  address?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  companyName?: T;
  registrationNumber?: T;
  vatNumber?: T;
  registeredAddress?: T;
  tradeRegisterInfo?: T;
  shippingRates?:
    | T
    | {
        econtOffice?: T;
        econtAddress?: T;
        speedyOffice?: T;
        speedyAddress?: T;
        freeShippingThreshold?: T;
      };
  shippingInfo?: T;
  footerText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}